name: Likenft-indexer-test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: likenft-indexer

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: likenft-indexer
          sparse-checkout-cone-mode: false
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'

      - name: Install templ
        shell: bash
        run: go install github.com/a-h/templ/cmd/templ@latest
      - name: Run templ generate
        shell: bash
        run: templ generate -path .

      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test ./... 